/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#005e64",
        "surface-bright": "#2c2b33",
        "surface-container-highest": "#25252c",
        "on-secondary": "#390050",
        "inverse-primary": "#006a71",
        "tertiary-fixed-dim": "#2be800",
        "on-error": "#490006",
        "on-secondary-fixed-variant": "#8300b4",
        "surface": "#0e0e13",
        "outline-variant": "#48474d",
        "primary-container": "#00eefc",
        "on-tertiary": "#0d6100",
        "surface-container": "#19191f",
        "primary-dim": "#00deec",
        "tertiary-container": "#2ff801",
        "tertiary-dim": "#2be800",
        "primary-fixed-dim": "#00deec",
        "primary": "#8ff5ff",
        "surface-dim": "#0e0e13",
        "surface-container-high": "#1f1f26",
        "primary-fixed": "#00eefc",
        "outline": "#76747b",
        "inverse-surface": "#fbf8ff",
        "on-primary-container": "#005359",
        "surface-container-low": "#131318",
        "on-secondary-fixed": "#58007a",
        "on-background": "#f8f5fd",
        "error-dim": "#d7383b",
        "on-tertiary-fixed": "#064200",
        "tertiary": "#8eff71",
        "surface-variant": "#25252c",
        "secondary-fixed-dim": "#eaaeff",
        "secondary-fixed": "#f0c1ff",
        "on-secondary-container": "#fff5fc",
        "secondary-container": "#9800d0",
        "on-primary": "#005d63",
        "on-tertiary-fixed-variant": "#0d6200",
        "surface-tint": "#8ff5ff",
        "on-primary-fixed": "#003f43",
        "error-container": "#9f0519",
        "surface-container-lowest": "#000000",
        "on-surface-variant": "#acaab1",
        "on-error-container": "#ffa8a3",
        "background": "#0e0e13",
        "secondary": "#d575ff",
        "on-tertiary-container": "#0b5800",
        "tertiary-fixed": "#2ff801",
        "on-surface": "#f8f5fd",
        "inverse-on-surface": "#55545a",
        "error": "#ff716c",
        "secondary-dim": "#b90afc"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "space-grotesk": ["Space Grotesk", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
